# Generated by Django 6.0.5 on 2026-06-26 09:58

import django.db.models.deletion
import users.models.Custom_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('users', '0002_remove_customuser_address_remove_customuser_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.Custom_user.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('owner', 'Owner'), ('guardian', 'Guardian'), ('vendor', 'Vendor')], help_text='Top-level role. Granular positions for Staff users are assigned separately via UserRole -> Role.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organization.organization'),
        ),
    ]
