# Generated by Django 6.0.5 on 2026-06-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_address_customuser_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('unclaimed', 'Unclaimed')], default='unclaimed', max_length=10),
        ),
    ]
