# Generated by Django 6.0.5 on 2026-06-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='organizations/logos/')),
                ('address', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('cover_picture', models.ImageField(upload_to='organizations/covers/')),
                ('domain_name', models.URLField()),
            ],
        ),
    ]
