# Generated by Django 6.0.5 on 2026-06-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='admin',
        ),
        migrations.AlterField(
            model_name='organization',
            name='domain_name',
            field=models.CharField(max_length=253, unique=True),
        ),
    ]
