# Generated by Django 6.0.5 on 2026-06-12 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organization', '0004_organization_created_at_organization_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='core.addressdetail'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='core.contactdetail'),
        ),
        migrations.AddField(
            model_name='organization',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='core.documentdetail'),
        ),
        migrations.CreateModel(
            name='SubOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suborg', to='core.addressdetail')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suborg', to='core.contactdetail')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborgs', to='organization.organization')),
            ],
            options={
                'unique_together': {('name', 'org')},
            },
        ),
    ]
