# Generated by Django 6.0.5 on 2026-06-15 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_address_detail_organization_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborganization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
