# Generated by Django 6.0.5 on 2026-06-15 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetail',
            name='uuid',
        ),
    ]
