# Generated by Django 6.0.5 on 2026-06-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_addressdetail_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdetail',
            name='birth_certificate_registration',
            field=models.FileField(blank=True, null=True, upload_to='documents/birth_certificate/'),
        ),
        migrations.AlterField(
            model_name='documentdetail',
            name='id_registration',
            field=models.FileField(blank=True, null=True, upload_to='documents/id/'),
        ),
        migrations.AlterField(
            model_name='documentdetail',
            name='tax_registration',
            field=models.FileField(blank=True, null=True, upload_to='documents/tax/'),
        ),
    ]
