# Generated by Django 6.0.5 on 2026-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_repr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated'), ('ASSIGNED', 'Assigned'), ('REVOKED', 'Revoked'), ('LOGIN', 'Logged in'), ('LOGOUT', 'Logged out'), ('LOGIN_FAILED', 'Failed login attempt')], default='CREATED', max_length=20),
            preserve_default=False,
        ),
    ]
