# Generated by Django 6.0.5 on 2026-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollevel',
            name='name',
            field=models.CharField(choices=[('pre_school', 'Pre School'), ('pre_primary', 'Pre Primary'), ('primary', 'Primary'), ('lower_secondary', 'Lower Secondary'), ('secondary', 'Secondary'), ('higher_secondary', 'Higher Secondary')], max_length=50),
        ),
    ]
