# Generated by Django 6.0.5 on 2026-06-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_alter_schoollevel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
