# Generated by Django 6.0.5 on 2026-06-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_alter_stream_name'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='Academics.grade')),
                ('streams', models.ManyToManyField(blank=True, help_text='Which streams this config applies to. Leave blank if the grade has no streams.', related_name='subject_configs', to='Academics.stream')),
            ],
            options={
                'ordering': ['grade__order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short identifier, unique within the org (e.g. ENG-101).', max_length=20)),
                ('book_publication', models.CharField(blank=True, help_text='Publisher or book title. Optional.', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='organization.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_compulsory', models.BooleanField(default=True, help_text='True = every student must take this subject.')),
                ('is_active', models.BooleanField(default=True)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='Academics.sem')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_subjects', to='Academics.subject')),
            ],
            options={
                'ordering': ['sem__order', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='OptionalSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human label for this group, e.g. 'Mathematics Group', 'Group A'.", max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_groups', to='Academics.classsubjectconfig')),
                ('subjects', models.ManyToManyField(help_text='Subjects in this group. Student picks exactly one.', related_name='optional_groups', to='Academics.subject')),
            ],
            options={
                'ordering': ['config', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classsubjectconfig',
            name='compulsory_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects every student in this config must take.', related_name='compulsory_configs', to='Academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='unique_subject_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='unique_subject_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='semestersubject',
            constraint=models.UniqueConstraint(fields=('sem', 'subject'), name='unique_subject_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='optionalsubjectgroup',
            constraint=models.UniqueConstraint(fields=('config', 'name'), name='unique_optional_group_name_per_config'),
        ),
    ]
