# Generated by Django 6.0.5 on 2026-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0004_classsubjectconfig_subject_semestersubject_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semestersubject',
            name='unique_subject_per_semester',
        ),
        migrations.AddField(
            model_name='classsubjectconfig',
            name='total_compulsory_subjects',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of compulsory subjects allowed for this config. 0 means no limit is set yet.'),
        ),
        migrations.AddField(
            model_name='classsubjectconfig',
            name='total_optional_groups',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of optional subject groups allowed for this config. 0 means no limit is set yet.'),
        ),
        migrations.AddField(
            model_name='sem',
            name='compulsory_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects every student in this semester must take.', related_name='compulsory_sems', to='Academics.subject'),
        ),
        migrations.AddField(
            model_name='sem',
            name='optional_subjects',
            field=models.ManyToManyField(blank=True, help_text='Pool of optional subjects for this semester. Students pick from these based on optional groups defined separately.', related_name='optional_sems', to='Academics.subject'),
        ),
        migrations.AddField(
            model_name='sem',
            name='total_compulsory_subjects',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of compulsory subjects allowed in this semester. compulsory_subjects.count() must not exceed this. 0 = not yet defined.'),
        ),
        migrations.AddField(
            model_name='sem',
            name='total_optional_subjects',
            field=models.PositiveIntegerField(default=0, help_text='Number of optional subject slots a student must fill in this semester. Mirrors the number of optional groups expected. 0 = not yet defined.'),
        ),
        migrations.AddField(
            model_name='sem',
            name='total_subjects',
            field=models.PositiveIntegerField(default=0, help_text='Total number of subjects a student takes in this semester (compulsory + one per optional group). 0 = not yet defined.'),
        ),
        migrations.DeleteModel(
            name='SemesterSubject',
        ),
    ]
