# Generated by Django 6.0.5 on 2026-06-26 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_remove_semestersubject_unique_subject_per_semester_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sem',
            name='unique_academic_year_name_per_program',
        ),
        migrations.RemoveConstraint(
            model_name='sem',
            name='unique_academic_year_order_per_program',
        ),
        migrations.AddField(
            model_name='sem',
            name='total_optional_groups',
            field=models.PositiveIntegerField(default=0, help_text='Maximum optional groups allowed. OptionalSubjectGroup count must not exceed this. 0 = no limit defined.'),
        ),
        migrations.AlterField(
            model_name='sem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Academics.program'),
        ),
        migrations.AlterField(
            model_name='sem',
            name='total_compulsory_subjects',
            field=models.PositiveIntegerField(default=0, help_text='Maximum compulsory subjects allowed. compulsory_subjects.count() must not exceed this. 0 = no limit defined.'),
        ),
        migrations.AddConstraint(
            model_name='sem',
            constraint=models.UniqueConstraint(fields=('program', 'name'), name='unique_sem_name_per_program'),
        ),
        migrations.AddConstraint(
            model_name='sem',
            constraint=models.UniqueConstraint(fields=('program', 'order'), name='unique_sem_order_per_program'),
        ),
        migrations.RemoveField(
            model_name='sem',
            name='optional_subjects',
        ),
        migrations.RemoveField(
            model_name='sem',
            name='total_optional_subjects',
        ),
        migrations.RemoveField(
            model_name='sem',
            name='total_subjects',
        ),
    ]
