# Generated by Django 6.0.5 on 2026-06-26 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0006_remove_sem_unique_academic_year_name_per_program_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalsubjectgroup',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='optionalsubjectgroup',
            name='unique_optional_group_name_per_config',
        ),
        migrations.AddField(
            model_name='optionalsubjectgroup',
            name='sem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optional_groups', to='Academics.sem'),
        ),
        migrations.AlterField(
            model_name='classsubjectconfig',
            name='total_compulsory_subjects',
            field=models.PositiveIntegerField(default=0, help_text='Maximum compulsory subjects allowed. 0 = no limit defined.'),
        ),
        migrations.AlterField(
            model_name='classsubjectconfig',
            name='total_optional_groups',
            field=models.PositiveIntegerField(default=0, help_text='Maximum optional groups allowed. 0 = no limit defined.'),
        ),
        migrations.AlterField(
            model_name='optionalsubjectgroup',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optional_groups', to='Academics.classsubjectconfig'),
        ),
        migrations.AlterField(
            model_name='optionalsubjectgroup',
            name='name',
            field=models.CharField(help_text="Human label, e.g. 'Mathematics Group', 'Group A'.", max_length=100),
        ),
        migrations.AddConstraint(
            model_name='optionalsubjectgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('sem__isnull', False)), fields=('sem', 'name'), name='unique_optional_group_name_per_sem'),
        ),
        migrations.AddConstraint(
            model_name='optionalsubjectgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('config__isnull', False)), fields=('config', 'name'), name='unique_optional_group_name_per_config'),
        ),
    ]
